extends: "eslint:recommended"

plugins:
  - react
env:
  browser: true
  commonjs: true
  es6: true
parserOptions:
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  react/jsx-uses-vars: 1
  react/jsx-uses-react: 1
  no-unused-vars: warn
  no-const-assign: warn
  no-this-before-super: warn
  no-undef: warn
  no-unreachable: warn
  constructor-super: warn
  valid-typeof: warn
